### ISSUE TITLE
Still have problem with multiple attach schema???

### ISSUE THREAD

**Issue by thearabbit** [Meteor-Community-Packages/meteor-collection2#373] opened 2018-02-17 14:53 UTC
Excuse me, I still have problem with `multiple attach schema`
(I would like to create `collection behaviours`)
```js
// Soft Remove
CollectionExtensions.addPrototype('softRemove', function(selector = {}) {
  let self = this
  const schema = new SimpleSchema({
    removed: {
      type: Boolean,
    },
    removedAt: {
      type: Date,
    },
    removedBy: {
      type: String,
    },
  })
  self.attachSchema(schema, {selector: {type: 'softRemove'}});

  return self.direct.update(
    selector,
    {
      $set: {
        removed: true,
        removedAt: new Date(),
        removedBy: Meteor.userId(),
      },
    },
    {
      multi: true,
      selector: {type: 'softRemove'}
    },
    (error, result) => {
      if (result) {
        console.log('soft-remove')
      }
    }
  )
})
```
But have problem when I update collection, It is required `soft remove field`
Please help me

**Comment by aldeed** [comment] 2018-04-11 23:05
This should work. You would need to post the full error you get or a full reproduction

**Comment by StorytellerCZ** [comment] 2022-10-10 13:47
Closing due to lack of reproduction.

**Closed by StorytellerCZ** 2022-10-10 13:47 UTC
Labels: needs reproduction, potential bug
